---
- name: Ensure ~/.local/bin directory exists
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.local/bin"
    state: directory
    mode: "0700"

- name: Find extra-executable scripts in the playbook directory
  ansible.builtin.find:
    paths: "{{ playbook_dir }}/files/executable-scripts"
  register: executable_scripts_files
  delegate_to: localhost
  run_once: true

- name: Copy extra-executable scripts to ~/.local/bin
  ansible.builtin.copy:
    src: "{{ item.path }}"
    dest: "{{ ansible_env.HOME }}/.local/bin/{{ item.path | basename }}"
    mode: "0700"
  loop: "{{ executable_scripts_files.files | selectattr('isreg') | list }}"
